In [52]:
import sys
import os

# Adds the parent directory to the python path
sys.path.append(os.path.abspath(os.path.join('..')))

In [53]:
from src.data.preprocessing import (
    load_imdb_data,
    create_train_validation_split,
)

train_data, test_data = load_imdb_data()

In [54]:
print(train_data)
print(test_data)

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})
Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})


In [55]:
print(train_data[0])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [56]:
train_texts, train_labels, val_texts, val_labels = (
    create_train_validation_split(train_data)
)

In [57]:
print(len(train_texts))
print(len(val_texts))

20000
5000


### Tokenization test

In [58]:
from src.data.vocabulary import Vocabulary

vocab = Vocabulary()

text = "This movie was absolutely AMAZING!"

tokens = vocab.tokenize(text)

print(tokens)

['this', 'movie', 'was', 'absolutely', 'amazing']


In [59]:
from src.data.vocabulary import Vocabulary

In [60]:
from src.data.preprocessing import (
    load_imdb_data,
    create_train_validation_split,
)

train_data, test_data = load_imdb_data()

(
    train_texts,
    train_labels,
    val_texts,
    val_labels,
) = create_train_validation_split(
    train_data
)

In [61]:
vocab = Vocabulary(
    max_size=10000
)

vocab.build(train_texts)

In [62]:
print(len(vocab.word_to_id))

10000


In [63]:
print(list(vocab.word_to_id.items())[:20])

[('<PAD>', 0), ('<UNK>', 1), ('the', 2), ('and', 3), ('a', 4), ('of', 5), ('to', 6), ('is', 7), ('in', 8), ('it', 9), ('i', 10), ('this', 11), ('that', 12), ('br', 13), ('was', 14), ('as', 15), ('for', 16), ('with', 17), ('but', 18), ('movie', 19)]


In [64]:
text = "this movie was amazing"

encoded = vocab.encode(text)

print(encoded)

[11, 19, 14, 467]


In [65]:
## testing the <UNK> behaviour

text = "xyzabc123notaword"

encoded = vocab.encode(text)

print(encoded)

[1]


### testing tokenization, encoding, unknown words, padding, full pipeline.

In [66]:
from src.data.vocabulary import Vocabulary

In [67]:
vocab = Vocabulary(
    max_size=10000
)

In [68]:
text = "This movie was AMAZING!"

tokens = vocab.tokenize(text)

print(tokens)

['this', 'movie', 'was', 'amazing']


In [69]:
encoded = vocab.encode(
    "this movie was amazing"
)

print(encoded)

[1, 1, 1, 1]


In [70]:
encoded = vocab.encode(
    "completelyunknownwordxyz"
)

print(encoded)

[1]


In [71]:
padded = vocab.pad_sequence(
    [1, 2, 3],
    max_length=5
)

print(padded)

[1, 2, 3, 0, 0]


In [72]:
encoded = vocab.encode_and_pad(
    "This movie was absolutely amazing!",
    max_length=500,
)

print(len(encoded))
print(encoded[:10])
print(encoded[-10:])

500
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


### now we will test the dataset

In [73]:
from src.data.preprocessing import (
    load_imdb_data,
    create_train_validation_split,
)

train_data, test_data = load_imdb_data()

(
    train_texts,
    train_labels,
    val_texts,
    val_labels,
) = create_train_validation_split(
    train_data
)

In [74]:
from src.data.dataset import IMDBDataset

In [75]:
from src.data.vocabulary import Vocabulary

vocab = Vocabulary(
    max_size=10000
)

In [76]:
train_dataset = IMDBDataset(
    texts=train_texts,
    labels=train_labels,
    vocabulary=vocab,
    max_length=500,
)

val_dataset = IMDBDataset(
    texts=val_texts,
    labels=val_labels,
    vocabulary=vocab,
    max_length=500,
)

test_dataset = IMDBDataset(
    texts=test_data["text"],
    labels=test_data["label"],
    vocabulary=vocab,
    max_length=500,
)

In [77]:
print(len(train_dataset))
print(len(val_dataset))
print(len(test_dataset))

20000
5000
25000


In [78]:
train_dataset[0]

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1

In [79]:
from src.data.dataloader import create_dataloaders

train_loader, val_loader, test_loader = create_dataloaders(
    train_dataset,
    val_dataset,
    test_dataset,
    batch_size=32,
)

batch_x, batch_y = next(iter(train_loader))

print(batch_x.shape)
print(batch_y.shape)

torch.Size([32, 500])
torch.Size([32])


In [80]:
x, y = train_dataset[0]

print(x.shape)
print(x.dtype)

print(y)
print(y.dtype)

torch.Size([500])
torch.int64
tensor(1.)
torch.float32


In [81]:
from src.data.dataloader import create_dataloaders

(
    train_loader,
    val_loader,
    test_loader,
) = create_dataloaders(
    train_dataset,
    val_dataset,
    test_dataset,
    batch_size=32,
)

In [82]:
batch_x, batch_y = next(iter(train_loader))

print(batch_x.shape)
print(batch_y.shape)

torch.Size([32, 500])
torch.Size([32])


In [83]:
## lets make sure the data loader isn't accidentally changing out token ID's

print(batch_x[0])

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [84]:
print(batch_x[0].shape)

torch.Size([500])


In [85]:
print(batch_y)

tensor([0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.])


In [86]:
unknown_count = (batch_x == 1).sum().item()
padding_count = (batch_x == 0).sum().item()

total_tokens = batch_x.numel()

print("Unknown tokens:", unknown_count)
print("Padding tokens:", padding_count)
print("Total tokens:", total_tokens)

print(
    "Unknown percentage:",
    unknown_count / total_tokens * 100
)

print(
    "Padding percentage:",
    padding_count / total_tokens * 100
)

Unknown tokens: 6630
Padding tokens: 9370
Total tokens: 16000
Unknown percentage: 41.4375
Padding percentage: 58.56249999999999


In [87]:
print(train_texts[0][:1000])

I have always been a huge James Bond fanatic! I have seen almost all of the films except for Die Another Day, and The World Is Not Enough. The graphic's for Everything Or Nothing are breathtaking! The voice talents......... WOW! I LOVE PIERCE BROSNAN! He is finally Bond in a video game! HE IS BOND! I enjoyed the past Bond games: Goldeneye, The World Is Not Enough, Agent Under Fire, and Nightfire. This one is definitely the best! Finally, Mr. Brosnan, (may I call him Mr. Brosnan as a sign of respect? Yes I can!) He was phenomenally exciting to hear in a video game....... AT LONG LAST! DUH! I've seen him perform with Robin Williams, and let me tell you, they make a great team. Pierce Brosnan is funny, wickedly handsome ( I mean to say wickedly in a good way,) and just one of those actor's who you would want to walk up to and wrap your arms around and hug, saying: "Pierce Brosnan, thank you for being James Bond," "If it wasn't for you, I wouldn't know who James Bond is." He's a great acto

In [88]:
x, y = train_dataset[0]

print(x[:100])

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])


In [89]:
print("Vocabulary size:", len(vocab.word_to_id))

print(
    list(vocab.word_to_id.items())[:30]
)

Vocabulary size: 2
[('<PAD>', 0), ('<UNK>', 1)]


In [90]:
for word in [
    "the",
    "and",
    "a",
    "i",
    "have",
    "movie",
    "bond",
    "james",
]:
    print(word, "->", vocab.word_to_id.get(word))

the -> None
and -> None
a -> None
i -> None
have -> None
movie -> None
bond -> None
james -> None


In [91]:
text = train_texts[0]

tokens = vocab.tokenize(text)

print(tokens[:30])

['i', 'have', 'always', 'been', 'a', 'huge', 'james', 'bond', 'fanatic', 'i', 'have', 'seen', 'almost', 'all', 'of', 'the', 'films', 'except', 'for', 'die', 'another', 'day', 'and', 'the', 'world', 'is', 'not', 'enough', 'the', 'graphics']


In [92]:
print(vocab.encode(text)[:30])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [93]:
print(len(vocab.word_to_id))
print(list(vocab.word_to_id.items())[:20])

2
[('<PAD>', 0), ('<UNK>', 1)]


In [94]:
for word in ["the", "and", "a", "i", "have", "movie", "bond", "james"]:
    print(word, "->", vocab.word_to_id.get(word))

the -> None
and -> None
a -> None
i -> None
have -> None
movie -> None
bond -> None
james -> None


In [95]:
tokens = vocab.tokenize(train_texts[0])
encoded = vocab.encode(train_texts[0])

for token, token_id in zip(tokens[:20], encoded[:20]):
    print(f"{token:15} -> {token_id}")

i               -> 1
have            -> 1
always          -> 1
been            -> 1
a               -> 1
huge            -> 1
james           -> 1
bond            -> 1
fanatic         -> 1
i               -> 1
have            -> 1
seen            -> 1
almost          -> 1
all             -> 1
of              -> 1
the             -> 1
films           -> 1
except          -> 1
for             -> 1
die             -> 1


## debug for Vocabulary.build() directly

In [96]:
print("max_size:", vocab.max_size)

max_size: 10000


In [97]:
from collections import Counter

counter = Counter()

for text in train_texts[:5]:
    tokens = vocab.tokenize(text)
    counter.update(tokens)

print("Number of unique words:", len(counter))
print("Most common words:", counter.most_common(20))

Number of unique words: 668
Most common words: [('the', 75), ('and', 53), ('a', 49), ('of', 39), ('to', 37), ('i', 32), ('in', 32), ('is', 26), ('it', 20), ('was', 18), ('for', 17), ('as', 15), ('this', 14), ('that', 13), ('movie', 13), ('br', 13), ('with', 11), ('not', 10), ('film', 10), ('one', 9)]


In [98]:
import inspect

print(inspect.getsource(Vocabulary.build))

    def build(self, texts):

        counter = Counter()

        for text in texts:

            tokens = self.tokenize(text)

            counter.update(tokens)

        most_common = counter.most_common(
            self.max_size - 2
        )

        for idx, (word, _) in enumerate(
            most_common,
            start=2,
        ):

            self.word_to_id[word] = idx

            self.id_to_word[idx] = word



### Direct test

In [99]:
test_vocab = Vocabulary(max_size=10000)

In [100]:
test_vocab.build([
    "the movie was amazing",
    "the movie was fantastic",
    "i loved the movie",
])

In [101]:
print(test_vocab.word_to_id)

{'<PAD>': 0, '<UNK>': 1, 'the': 2, 'movie': 3, 'was': 4, 'amazing': 5, 'fantastic': 6, 'i': 7, 'loved': 8}


In [102]:
print("Vocabulary size:", len(vocab.word_to_id))

Vocabulary size: 2


In [103]:
import inspect

print(inspect.getsource(Vocabulary.build))

    def build(self, texts):

        counter = Counter()

        for text in texts:

            tokens = self.tokenize(text)

            counter.update(tokens)

        most_common = counter.most_common(
            self.max_size - 2
        )

        for idx, (word, _) in enumerate(
            most_common,
            start=2,
        ):

            self.word_to_id[word] = idx

            self.id_to_word[idx] = word



In [104]:
test_vocab = Vocabulary(max_size=10000)

text = "the movie was amazing"

tokens = test_vocab.tokenize(text)

print(tokens)

['the', 'movie', 'was', 'amazing']


In [105]:
from collections import Counter

counter = Counter()

for text in [
    "the movie was amazing",
    "the movie was fantastic",
    "i loved the movie",
]:
    tokens = test_vocab.tokenize(text)
    counter.update(tokens)

print(counter)
print(counter.most_common(10))

Counter({'the': 3, 'movie': 3, 'was': 2, 'amazing': 1, 'fantastic': 1, 'i': 1, 'loved': 1})
[('the', 3), ('movie', 3), ('was', 2), ('amazing', 1), ('fantastic', 1), ('i', 1), ('loved', 1)]


In [106]:
test_vocab = Vocabulary(max_size=10000)

test_vocab.build([
    "the movie was amazing",
    "the movie was fantastic",
    "i loved the movie",
])

print(len(test_vocab.word_to_id))
print(test_vocab.word_to_id)

9
{'<PAD>': 0, '<UNK>': 1, 'the': 2, 'movie': 3, 'was': 4, 'amazing': 5, 'fantastic': 6, 'i': 7, 'loved': 8}


In [107]:
print(type(train_texts))
print(len(train_texts))
print(repr(train_texts[0][:200]))

<class 'list'>
20000
"I have always been a huge James Bond fanatic! I have seen almost all of the films except for Die Another Day, and The World Is Not Enough. The graphic's for Everything Or Nothing are breathtaking! The"


In [108]:
print(vocab.tokenize(train_texts[0])[:30])

['i', 'have', 'always', 'been', 'a', 'huge', 'james', 'bond', 'fanatic', 'i', 'have', 'seen', 'almost', 'all', 'of', 'the', 'films', 'except', 'for', 'die', 'another', 'day', 'and', 'the', 'world', 'is', 'not', 'enough', 'the', 'graphics']


In [109]:
counter = Counter()

for text in train_texts[:100]:
    counter.update(vocab.tokenize(text))

print("Unique tokens:", len(counter))
print(counter.most_common(20))

Unique tokens: 5017
[('the', 1454), ('and', 708), ('a', 691), ('to', 565), ('of', 520), ('in', 428), ('is', 380), ('i', 328), ('it', 285), ('this', 284), ('that', 226), ('br', 226), ('was', 205), ('with', 204), ('for', 199), ('but', 198), ('as', 189), ('movie', 176), ('his', 152), ('on', 139)]


In [111]:
test_vocab = Vocabulary(max_size=10000)

test_vocab.build([
    "the movie was amazing",
    "the movie was fantastic",
    "i loved the movie",
])

print("Vocabulary size:", len(test_vocab.word_to_id))
print(test_vocab.word_to_id)

Vocabulary size: 9
{'<PAD>': 0, '<UNK>': 1, 'the': 2, 'movie': 3, 'was': 4, 'amazing': 5, 'fantastic': 6, 'i': 7, 'loved': 8}


In [112]:
most_common = counter.most_common(10000 - 2)

print("Number of words:", len(most_common))
print(most_common[:10])

Number of words: 5017
[('the', 1454), ('and', 708), ('a', 691), ('to', 565), ('of', 520), ('in', 428), ('is', 380), ('i', 328), ('it', 285), ('this', 284)]


In [113]:
for idx, (word, _) in enumerate(
    most_common,
    start=2,
):
    print(idx, word)
    
    if idx == 10:
        break

2 the
3 and
4 a
5 to
6 of
7 in
8 is
9 i
10 it


In [114]:
## testing everthing in one cell
from src.data.vocabulary import Vocabulary

vocab = Vocabulary(max_size=10000)

print("Before build:")
print(len(vocab.word_to_id))

vocab.build(train_texts)

print("\nAfter build:")
print(len(vocab.word_to_id))

print("\nFirst 20 words:")
print(list(vocab.word_to_id.items())[:20])

Before build:
2

After build:
10000

First 20 words:
[('<PAD>', 0), ('<UNK>', 1), ('the', 2), ('and', 3), ('a', 4), ('of', 5), ('to', 6), ('is', 7), ('in', 8), ('it', 9), ('i', 10), ('this', 11), ('that', 12), ('br', 13), ('was', 14), ('as', 15), ('for', 16), ('with', 17), ('but', 18), ('movie', 19)]


In [115]:
tokens = vocab.tokenize(train_texts[0])
encoded = vocab.encode(train_texts[0])

for token, token_id in zip(tokens[:20], encoded[:20]):
    print(f"{token:15} -> {token_id}")

i               -> 10
have            -> 26
always          -> 204
been            -> 77
a               -> 4
huge            -> 640
james           -> 555
bond            -> 1525
fanatic         -> 7076
i               -> 10
have            -> 26
seen            -> 107
almost          -> 215
all             -> 32
of              -> 5
the             -> 2
films           -> 97
except          -> 538
for             -> 16
die             -> 846


#### recreating

In [116]:
from src.data.dataset import IMDBDataset

train_dataset = IMDBDataset(
    texts=train_texts,
    labels=train_labels,
    vocabulary=vocab,
    max_length=500,
)

val_dataset = IMDBDataset(
    texts=val_texts,
    labels=val_labels,
    vocabulary=vocab,
    max_length=500,
)

test_dataset = IMDBDataset(
    texts=test_data["text"],
    labels=test_data["label"],
    vocabulary=vocab,
    max_length=500,
)

In [117]:
from src.data.dataloader import create_dataloaders

train_loader, val_loader, test_loader = create_dataloaders(
    train_dataset,
    val_dataset,
    test_dataset,
    batch_size=32,
)

In [118]:
## checking actual batch again
batch_x, batch_y = next(iter(train_loader))

unknown_count = (batch_x == 1).sum().item()
padding_count = (batch_x == 0).sum().item()
total_tokens = batch_x.numel()

print("Unknown tokens:", unknown_count)
print("Padding tokens:", padding_count)
print("Total tokens:", total_tokens)

print(
    "Unknown percentage:",
    unknown_count / total_tokens * 100
)

print(
    "Padding percentage:",
    padding_count / total_tokens * 100
)

Unknown tokens: 455
Padding tokens: 8684
Total tokens: 16000
Unknown percentage: 2.84375
Padding percentage: 54.275
